sfdx/sfdxtest1/force-app/main/default/objects/EstimateDetail__c/EstimateDetail__c.object-meta.xml
<CustomObject>
    <label>見積明細</label>
    <nameField>
        <displayFormat>E#-{0000}</displayFormat>
        <label>見積明細番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx/sfdxtest1/force-app/main/default/objects/EstimateDetail__c/fields/Approvar1__c.field-meta.xml
<CustomField>
    <fullName>Approvar1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>承認者（課長）</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ApprovarParent1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx/sfdxtest1/force-app/main/default/objects/EstimateDetail__c/fields/Approvar2__c.field-meta.xml
<CustomField>
    <fullName>Approvar2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>承認者（部長）</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ApprovarParent2</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx/sfdxtest1/force-app/main/default/objects/EstimateInfo__c/EstimateInfo__c.object-meta.xml
<CustomObject>
    <label>見積情報</label>
    <nameField>
        <label>見積情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/sfdxtest1/force-app/main/default/objects/EstimateInfo__c/fields/Approvar1__c.field-meta.xml
<CustomField>
    <fullName>Approvar1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>承認者（課長）</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvar1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx/sfdxtest1/force-app/main/default/objects/EstimateInfo__c/fields/Approvar2__c.field-meta.xml
<CustomField>
    <fullName>Approvar2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>承認者（部長）</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvar2</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx/sfdxtest1/force-app/main/default/classes/EstimateDataUtil.cls
public with sharing class EstimateDataUtil {
    public static Boolean CopyInfoData2Detail(EstimateInfo__c parent, EstimateDetail__c child){
    	Boolean bUpd = false;
    	
    	if (parent != null && child != null){
	    	// 承認者のコピー
	    	if (child.Approvar1__c != parent.Approvar1__c) {
				child.Approvar1__c = parent.Approvar1__c;
				bUpd = true;
	    	}
	    	if (child.Approvar2__c != parent.Approvar2__c) {		
				child.Approvar2__c = parent.Approvar2__c;
				bUpd = true;
	    	}
    		
    	}
    	
    	
    	
    	return bUpd;
    }
}